-- Carrega vendas do bileto
INSERT INTO [dbo].[dimVenda]
           ([is_bileto]
           ,[gateway]
           ,[numero_venda_ir]
           ,[venda_bilheteria_id]
           ,[codigo_gateway]
           ,[nsu_host]
           ,[nsu_sitef]
           ,[paypal_id]
           ,[numero_autorizacao_adquirente]
           ,[data_compra]
           ,[valor_taxa_conveniencia_total]
           ,[valor_taxa_entrega_total]
           ,[valor_juros_total]
           ,[valor_compra_original_total]
           ,[numero_cartao]
           ,[nome_portador_cartao]
           ,[status_compra]
           ,[nome_comprador]
           ,[telefone_comprador]
           ,[id_usuario]
           ,[ip_comprador]
           ,[plataforma_utilizada]
           ,[nota_fiscal_estabelecimento_sitef]
           ,[data_venda_completa]
           ,[nomes_precos_ingressos_unicos])
SELECT distinct a.[is_bileto]
      ,a.[gateway]
      ,a.[numero_venda_ir]
      ,a.[venda_bilheteria_id]
      ,a.[codigo_gateway]
      ,a.[nsu_host]
      ,a.[nsu_sitef]
      ,a.[paypal_id]
      ,a.[numero_autorizacao_adquirente]
      ,a.[data_compra]
      ,avg(a.[valor_taxa_conveniencia_total]) as ValorTaxaConvenienciaTotal -- Validar se deve ser somando ou média com o Brabo. 
      ,a.[valor_taxa_entrega_total]
      ,avg(a.[valor_juros_total]) as ValorJurosTotal -- Validar se deve ser somado ou média com o Brabo. 
      ,a.[valor_compra_original_total]
      ,a.[numero_cartao]
      ,a.[nome_portador_cartao]
      ,a.[status_compra]
      ,a.[nome_comprador]
      ,a.[telefone_comprador]
      ,a.[id_usuario]
      ,a.[ip_comprador]
      ,a.[plataforma_utilizada]
      ,a.[nota_fiscal_estabelecimento_sitef]
      ,a.[data_venda_completa]
      ,a.[nomes_precos_ingressos_unicos]
  FROM [dbo].[dsVendaAtivaBileto] a
  left join dimVenda b on a.numero_venda_ir = b.numero_venda_ir
						and a.is_bileto = b.is_bileto 
  where b.IdVenda is null 
  group by a.[is_bileto]
      ,a.[gateway]
      ,a.[numero_venda_ir]
      ,a.[venda_bilheteria_id]
      ,a.[codigo_gateway]
      ,a.[nsu_host]
      ,a.[nsu_sitef]
      ,a.[paypal_id]
      ,a.[numero_autorizacao_adquirente]
      ,a.[data_compra]
      ,a.[valor_taxa_entrega_total]
      ,a.[valor_compra_original_total]
      ,a.[numero_cartao]
      ,a.[nome_portador_cartao]
      ,a.[status_compra]
      ,a.[nome_comprador]
      ,a.[telefone_comprador]
      ,a.[id_usuario]
      ,a.[ip_comprador]
      ,a.[plataforma_utilizada]
      ,a.[nota_fiscal_estabelecimento_sitef]
      ,a.[data_venda_completa]
      ,a.[nomes_precos_ingressos_unicos]


--=================================================
-- Incluindo vendas do arquivo de cancelamentos
--=================================================
-- Carrega as vendas que ainda não foram carregadas
INSERT INTO [dbo].[dimVenda]
           ([is_bileto]
           ,[gateway]
           ,[numero_venda_ir]
           ,[venda_bilheteria_id]
           ,[codigo_gateway]
           ,[nsu_host]
           ,[nsu_sitef]
           ,[paypal_id]
           ,[numero_autorizacao_adquirente]
           ,[data_compra]
           ,[valor_juros_total]
           ,[valor_compra_original_total]
           ,[status_compra]
           ,[nome_comprador]
           ,[telefone_comprador]
           ,[id_usuario]
           ,[ip_comprador]
           ,[nota_fiscal_estabelecimento_sitef])
SELECT distinct a.[is_bileto]
      ,a.[gateway]
      ,a.[numero_venda_ir]
      ,a.[venda_bilheteria_id]
      ,a.[codigo_gateway]
      ,a.[nsu_host]
      ,a.[nsu_sitef]
      ,a.[paypal_id]
      ,a.[numero_autorizacao_adquirente]
      ,a.[data_compra]
      ,avg(a.[valor_juros_total]) as ValorJurosTotal
      ,a.[valor_compra_original_total]
      ,a.[status_compra]
      ,a.[nome_comprador]
      ,a.[telefone_comprador]
      ,a.[id_usuario]
      ,a.[ip_comprador]
      ,a.[nota_fiscal_estabelecimento_sitef]
  FROM [dbo].dsVendaCanceladaBileto a
  left join dimVenda b on a.numero_venda_ir = b.numero_venda_ir
						and a.is_bileto = b.is_bileto 
  where b.IdVenda is null
  group by a.[is_bileto]
      ,a.[gateway]
      ,a.[numero_venda_ir]
      ,a.[venda_bilheteria_id]
      ,a.[codigo_gateway]
      ,a.[nsu_host]
      ,a.[nsu_sitef]
      ,a.[paypal_id]
      ,a.[numero_autorizacao_adquirente]
      ,a.[data_compra]
      ,a.[valor_compra_original_total]
      ,a.[status_compra]
      ,a.[nome_comprador]
      ,a.[telefone_comprador]
      ,a.[id_usuario]
      ,a.[ip_comprador]
      ,a.[nota_fiscal_estabelecimento_sitef]
